name: Keep caches fresh
on:
    schedule:
        - cron: "5 4 1/4 * *" # every 4 days

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Set up notebook state cache
            uses: actions/cache@v5
            with:
                path: pluto_state_cache
                key: ${{ runner.os }}-pluto_state_cache-v3-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}-${{ github.run_id }}
                restore-keys: ${{ runner.os }}-pluto_state_cache-v3-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}
